# Generated by Django 5.0.2 on 2024-02-14 12:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Poi",
            fields=[
                (
                    "internal_id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                ("external_id", models.CharField(db_index=True, max_length=254)),
                ("name", models.CharField(max_length=254)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "ratings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), default=list, size=None
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="points_of_interests.category",
                    ),
                ),
            ],
        ),
    ]
